config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, path: 'employees', controllers: {
    sessions: 'employees/sessions',
    registrations: 'employees/registrations'
  }
  devise_for :users

  root "home#index"
  get '/orders/status', to: 'orders#status'
  post '/orders/check', to: 'orders#check'

  resources :restaurants do

    resources :employees, only: [:index, :new, :create, :destroy]

    resources :operating_days, only: [:new, :create, :update, :edit, :show]

    resources :markers, only: [:new, :create]

    resources :menus, only: [:new, :create, :show] do
      resources :menu_contents, only: [:new, :create, :show, :destroy]
    end

    resources :dishes do
      resources :servings, only: [:new, :create, :edit, :update, :destroy, :index, :show]
      post 'active', on: :member
      post 'inactive', on: :member

    end
    resources :beverages do
      resources :servings, only: [:new, :create, :edit, :update, :destroy, :index, :show]
      post 'active', on: :member
      post 'inactive', on: :member

    end

    resources :orders, only: [:new, :create, :show, :index] do
      post 'close_order', on: :member
      get 'result', on: :member
      resources :order_items, only: [:new, :create]
    end

    resources :discounts do
      resources :discount_servings, only: [:new, :create]
    end

  end
  get 'search', to: 'search#search'

  namespace :api do
    namespace :v1 do
      resources :restaurants do
        resources :orders, only: [:show, :index] do
          post 'in_preparation', on: :member
          post 'ready', on: :member
          post 'canceled', on: :member
        end
      end
    end
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  before_action :authenticate_user!
  before_action :set_restaurant
  
  def search
    query = "%#{params[:query].downcase}%"
    @dishes = @restaurant.dishes.where("LOWER(name) LIKE ? OR LOWER(description) LIKE ?", query, query)
    @beverages = @restaurant.beverages.where("LOWER(name) LIKE ? OR LOWER(description) LIKE ?", query, query)
  end

  def set_restaurant
    @restaurant = current_user.restaurant
  end
end

app/views/search/search.html.erb
<div class="container mx-auto px-5 mt-10">
  <h2 class="text-2xl font-bold text-gray-800 mb-6">Resultados da Busca</h2>

  <% if @dishes.any? || @beverages.any? %>
    <% if @dishes.any? %>
      <div class="mb-10">
        <h3 class="text-xl font-semibold text-blue-600 mb-4">Pratos</h3>
        <ul class="space-y-4">
          <% @dishes.each do |dish| %>
            <li class="flex items-center justify-between bg-white shadow-md rounded-md p-4 hover:shadow-lg transition-shadow">
              <div class="text-gray-800 font-medium">
                <%= link_to dish.name, restaurant_dish_path(@restaurant, dish), class: "text-blue-500 hover:underline" %>
              </div>
              <div>
                <%= link_to 'Editar', edit_restaurant_dish_path(@restaurant, dish), 
                  class: "text-sm text-white bg-blue-600 py-1 px-3 rounded-md hover:bg-blue-500 transition-colors" %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <% if @beverages.any? %>
      <div>
        <h3 class="text-xl font-semibold text-blue-600 mb-4">Bebidas</h3>
        <ul class="space-y-4">
          <% @beverages.each do |beverage| %>
            <li class="flex items-center justify-between bg-white shadow-md rounded-md p-4 hover:shadow-lg transition-shadow">
              <div class="text-gray-800 font-medium">
                <%= link_to beverage.name, restaurant_beverage_path(@restaurant, beverage), class: "text-blue-500 hover:underline" %>
              </div>
              <div>
                <%= link_to 'Editar', edit_restaurant_beverage_path(@restaurant, beverage), 
                  class: "text-sm text-white bg-blue-600 py-1 px-3 rounded-md hover:bg-blue-500 transition-colors" %>
              </div>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
  <% else %>
    <p class="text-gray-500">Nenhum resultado encontrado.</p>
  <% end %>
</div>