config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, path: 'employees', controllers: {
    sessions: 'employees/sessions',
    registrations: 'employees/registrations'
  }
  devise_for :users

  root "home#index"
  get '/orders/status', to: 'orders#status'
  post '/orders/check', to: 'orders#check'

  resources :restaurants do

    resources :employees, only: [:index, :new, :create, :destroy]

    resources :operating_days, only: [:new, :create, :update, :edit, :show]

    resources :markers, only: [:new, :create]

    resources :menus, only: [:new, :create, :show] do
      resources :menu_contents, only: [:new, :create, :show, :destroy]
    end

    resources :dishes do
      resources :servings, only: [:new, :create, :edit, :update, :destroy, :index, :show]
      post 'active', on: :member
      post 'inactive', on: :member

    end
    resources :beverages do
      resources :servings, only: [:new, :create, :edit, :update, :destroy, :index, :show]
      post 'active', on: :member
      post 'inactive', on: :member

    end

    resources :orders, only: [:new, :create, :show, :index] do
      post 'close_order', on: :member
      get 'result', on: :member
      resources :order_items, only: [:new, :create]
    end

    resources :discounts do
      resources :discount_servings, only: [:new, :create]
    end

  end
  get 'search', to: 'search#search'

  namespace :api do
    namespace :v1 do
      resources :restaurants do
        resources :orders, only: [:show, :index] do
          post 'in_preparation', on: :member
          post 'ready', on: :member
          post 'canceled', on: :member
        end
      end
    end
  end
end

app/views/shared/_employee_home.html.erb
<% if @menus.present? %>

  <div class="text-center ">
    <h1 class="text-4xl font-bold text-gray-800 py-5">Cardápios</h1>
    <% if @menus.present? %>
    <%= link_to 'Criar Novo Pedido', new_restaurant_order_path(@restaurant),
      class: "bg-indigo-600 text-white px-5 py-2 rounded-lg shadow-md hover:bg-indigo-500 focus:outline-none focus:ring focus:ring-indigo-300 text-sm font-medium" %>
    <% end %>
  </div>

  <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 py-3">
    <% @menus.each do |menu| %>
      <div id="menu_<%= menu.id %>" class="bg-white shadow-md rounded-lg p-6">
        <h3 class="text-xl font-semibold text-gray-800 mb-2">
          <%= link_to menu.name, restaurant_menu_path(@restaurant, menu), class: "hover:text-blue-600" %>
        </h3>
        <% menu.menu_items.active.each do |menu_item| %>
          <p class="text-gray-600 mb-4 px-2"><%= menu_item.name %></p>
        <% end %>
      </div>
    <% end %>
  </div>
<% else %>

  <div class="bg-white shadow-md rounded-lg p-6 text-center">
    <h2 class="text-xl text-gray-700 mb-4">Adicione cardápios para criar pedidos</h2>
  </div>

<% end %>