config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, path: 'employees', controllers: {
    sessions: 'employees/sessions',
    registrations: 'employees/registrations'
  }
  devise_for :users

  root "home#index"
  get '/orders/status', to: 'orders#status'
  post '/orders/check', to: 'orders#check'

  resources :restaurants do

    resources :employees, only: [:index, :new, :create, :destroy]

    resources :operating_days, only: [:new, :create, :update, :edit, :show]

    resources :markers, only: [:new, :create]

    resources :menus, only: [:new, :create, :show] do
      resources :menu_contents, only: [:new, :create, :show, :destroy]
    end

    resources :dishes do
      resources :servings, only: [:new, :create, :edit, :update, :destroy, :index, :show]
      post 'active', on: :member
      post 'inactive', on: :member

    end
    resources :beverages do
      resources :servings, only: [:new, :create, :edit, :update, :destroy, :index, :show]
      post 'active', on: :member
      post 'inactive', on: :member

    end

    resources :orders, only: [:new, :create, :show, :index] do
      post 'close_order', on: :member
      get 'result', on: :member
      resources :order_items, only: [:new, :create]
    end

    resources :discounts do
      resources :discount_servings, only: [:new, :create]
    end

  end
  get 'search', to: 'search#search'

  namespace :api do
    namespace :v1 do
      resources :restaurants do
        resources :orders, only: [:show, :index] do
          post 'in_preparation', on: :member
          post 'ready', on: :member
          post 'canceled', on: :member
        end
      end
    end
  end
end

app/models/dish.rb
class Dish < MenuItem

end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :restaurant

  has_many :servings

  has_many :menu_item_markers
  has_many :markers, through: :menu_item_markers

  has_many :menu_contents
  has_many :menus, through: :menu_contents

  has_one_attached :photo

  validates :name, :description, :restaurant, :status, presence: true
  enum :status, {:inactive=>0, :active=>1}

  scope :active, -> {where(status: 1)}
  scope :inactive, -> {where(status: 0)}

  validates :alcoholic, inclusion: { in: [true, false] }, if: :beverage?

  def beverage?
    type == "Beverage"
  end
end

app/controllers/dishes_controller.rb
class DishesController < ApplicationController
  before_action :authenticate_account!
  before_action :check_is_admin
  before_action :set_restaurant
  before_action :authorize_dish!, only: [:show, :active, :inactive, :edit, :index, :destroy, :new, :create, :update, :edit ]

  def index
    @dishes = @restaurant.dishes
  end

  def show
    @dish = @restaurant.dishes.find(params[:id])
  end

  def new
    @dish = @restaurant.dishes.build
  end

  def create
    @dish = @restaurant.dishes.build(dish_params)
    if @dish.save
      redirect_to @restaurant, notice: 'Prato Criado com sucesso!'
    else
      @markers = @restaurant.markers
      flash.now[:notice] = "Não foi possível cadastrar o prato!"
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @dish = @restaurant.dishes.find(params[:id])
    @markers = @restaurant.markers
  end

  def update
    @dish = @restaurant.dishes.find(params[:id])
    if @dish.update(dish_params)
      redirect_to restaurant_dish_path(@restaurant, @dish), notice: 'Prato atualizado com sucesso!'
    else
      @markers = @restaurant.markers
      flash.now[:notice] = 'Prato não Atualizado.'
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @dish = @restaurant.dishes.find(params[:id])
    @dish.destroy
    redirect_to restaurant_path(@restaurant), notice: 'Prato excluído com sucesso!'
  end

  def active
    @dish = @restaurant.dishes.find(params[:id])
    @dish.active!
    redirect_to restaurant_path(@restaurant), notice: "#{@dish.name} agora está ativo"
  end

  def inactive
    @dish = @restaurant.dishes.find(params[:id])
    @dish.inactive!
    redirect_to restaurant_path(@restaurant), notice: "#{@dish.name} agora está inativo"
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def dish_params
    params
    .require(:dish)
    .permit(
    :name,
    :description,
    :calories,
    :photo,
    marker_ids: []
    )
  end

  def authorize_dish!
    unless @restaurant.user_id == current_user.id
      redirect_to root_path, alert: 'Acesso negado!'
    end
  end
end
  

app/views/dishes/_form.html.erb
<div class="container mx-auto px-4 mt-8 max-w-4xl">
    <% if @dish.errors.any? %>
      <div class="bg-red-100 border-l-4 border-red-500 text-red-700 p-4 rounded-md mb-6">
        <% @dish.errors.full_messages.each do |message| %>
          <p class="text-sm"><%= message %></p>
        <% end %>
      </div>
    <% end %>
  <div class="bg-white shadow-md rounded-md p-6">
       <%= form_with(model: [@restaurant, @dish], class: "space-y-6") do |f| %>

      <div class="flex flex-col">
        <%= f.label :name, class: "block text-gray-700 font-medium mb-2" %>
        <%= f.text_field :name, required: true, class: "w-full bg-gray-50 border border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 py-2 px-3" %>
      </div>

      <div class="flex flex-col">
        <%= f.label :description, class: "block text-gray-700 font-medium mb-2" %>
        <%= f.text_area :description, required: true, class: "w-full bg-gray-50 border border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 py-2 px-3" %>
      </div>

      <div class="flex flex-col">
        <%= f.label :calories, class: "block text-gray-700 font-medium mb-2" %>
        <%= f.number_field :calories, class: "w-full bg-gray-50 border border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 py-2 px-3" %>
      </div>

      <div class="flex flex-col">
        <%= f.label :photo, class: "block text-gray-700 font-medium mb-2" %>
        <%= f.file_field :photo, accept: "image/png, image/jpg, image/jpeg", class: "w-full bg-gray-50 border border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500 py-2 px-3" %>
      </div>

      <div class="text-right mb-4">
        <%= link_to 'Adicionar Marcadores', new_restaurant_marker_path(@restaurant), class: "text-blue-600 hover:text-blue-700 font-medium" %>
      </div>

      <div class="flex flex-col">
        <%= f.label :markers, "Marcadores", class: "block text-gray-700 font-medium mb-2" %>
        <%= f.collection_check_boxes :marker_ids, Marker.all, :id, :name do |b| %>
          <div class="flex items-center space-x-2 mb-2">
            <%= b.check_box class: "h-4 w-4 text-blue-600 focus:ring-blue-500 border-gray-300 rounded" %>
            <%= b.label class: "text-gray-800" %>
          </div>
        <% end %>
      </div>

      <div class="text-right">
        <%= f.submit class: "py-2 px-4 bg-blue-600 text-white rounded shadow hover:bg-blue-700 focus:ring focus:ring-blue-500" %>
      </div>

    <% end %>
  </div>
</div>

app/views/dishes/edit.html.erb
<h1 class="text-2xl font-bold text-gray-800 mb-6">Editar Prato: <%= @dish.name %></h1>

<%= render "form" %>

<%= link_to 'Voltar para os detalhes do prato', restaurant_dish_path(@restaurant, @dish) %>

app/views/dishes/new.html.erb
<h1 class="text-2xl font-bold text-gray-800 mb-6">Adicionar Prato</h1>

<%= render "form" %>

<%= link_to 'Voltar', restaurant_path(@restaurant), class: "text-blue-600 hover:text-blue-700 font-medium" %>

app/views/dishes/show.html.erb
<div class="container mx-auto px-5 mt-10 max-w-4xl">

  <div class="bg-white shadow-md rounded-md p-6">

    <div class="mb-6 flex justify-center">
      <% if @dish.photo.attached? %>
        <div class="border-4 border-gray-300 p-4 rounded-lg shadow-lg">
          <%= image_tag @dish.photo, style: "max-width: 500px; max-height: 500px;", class: "rounded-lg shadow-xl" %>
        </div>
      <% else %>
        <p class="text-gray-600">Sem Imagem</p>
      <% end %>
    </div>

    <h1 class="text-3xl font-bold text-gray-800 mb-6 flex justify-center">
      <%= @dish.name %>
    </h1>

    <div class="mb-4">
      <strong class="text-lg text-gray-700">Descrição:</strong>
      <p class="text-gray-600"><%= @dish.description %></p>
    </div>

    <div class="mb-4">
      <strong class="text-lg text-gray-700">Calorias:</strong>
      <p class="text-gray-600">
        <%= @dish.calories.present? ? @dish.calories : "Não especificado" %>
      </p>
    </div>

    <div class="mb-4">
      <strong class="text-lg text-gray-700">Marcadores:</strong>
      <% if @dish.markers.any? %>
        <ul class="list-disc pl-5 text-gray-600">
          <% @dish.markers.each do |marker| %>
            <li><%= marker.name %></li>
          <% end %>
        </ul>
      <% else %>
        <p class="text-gray-600">Não há marcadores associados a este prato.</p>
      <% end %>
    </div>

    <div class="mb-4">
      <% if @dish.active? %>
        <%= button_to "Desativar Prato", inactive_restaurant_dish_path(@restaurant, @dish), class: "py-2 px-4 bg-red-600 text-white rounded-md shadow hover:bg-red-700 focus:ring focus:ring-red-500" %>
      <% else %>
        <%= button_to "Ativar Prato", active_restaurant_dish_path(@restaurant, @dish), class: "py-2 px-4 bg-green-600 text-white rounded-md shadow hover:bg-green-700 focus:ring focus:ring-green-500" %>
      <% end %>
    </div>

    <div class="mb-4">
      <%= link_to "Cadastrar Porção", new_restaurant_dish_serving_path(@restaurant, @dish), class: "text-blue-600 hover:text-blue-700 font-medium" %>
    </div>

    <div class="mb-4">
      <% if @dish.servings.empty? %>
        <p class="text-gray-500 italic">Não esqueça de adicionar porções para este prato!</p>
      <% else %>
        <% @dish.servings.each do |serving| %>
          <div class="mb-4 p-4 border border-gray-300 rounded-md shadow-sm">
            <h3 class="text-lg font-semibold text-gray-800"><%= serving.description %></h3>
            <p class="text-gray-600">Preço Atual: <%= number_to_currency(serving.price_display) %></p>
            <%= link_to "Atualizar Preço", edit_restaurant_dish_serving_path(@restaurant, @dish, serving), class: "text-blue-600 hover:text-blue-700 font-medium" %>
            <p class="mt-2 text-gray-700 font-semibold">Histórico de Preços:</p>
            <% serving.price_histories.each do |history| %>
              <div class="mt-2">
                <p class="text-gray-600">Preço: <%= number_to_currency(history.price_display) %></p>
                <p class="text-gray-600">Data de Atualização: <%= history.changed_at.strftime("%d/%m/%Y") %></p>
              </div>
            <% end %>
          </div>
        <% end %>
      <% end %>
    </div>

    <div class="mt-6 flex space-x-4">
      <%= link_to 'Editar Prato', edit_restaurant_dish_path(@restaurant, @dish), class: "text-blue-600 hover:text-blue-700 font-medium" %> 
      <%= button_to 'Excluir Prato', restaurant_dish_path(@restaurant, @dish), method: :delete, class: "text-red-600 hover:text-red-700 font-medium" %> 
      <%= link_to 'Voltar para o Restaurante', restaurant_path(@restaurant), class: "text-blue-600 hover:text-blue-700 font-medium" %>
    </div>
  </div>
</div>