config/routes.rb
Rails.application.routes.draw do
  devise_for :employees, path: 'employees', controllers: {
    sessions: 'employees/sessions',
    registrations: 'employees/registrations'
  }
  devise_for :users

  root "home#index"
  get '/orders/status', to: 'orders#status'
  post '/orders/check', to: 'orders#check'

  resources :restaurants do

    resources :employees, only: [:index, :new, :create, :destroy]

    resources :operating_days, only: [:new, :create, :update, :edit, :show]

    resources :markers, only: [:new, :create]

    resources :menus, only: [:new, :create, :show] do
      resources :menu_contents, only: [:new, :create, :show, :destroy]
    end

    resources :dishes do
      resources :servings, only: [:new, :create, :edit, :update, :destroy, :index, :show]
      post 'active', on: :member
      post 'inactive', on: :member

    end
    resources :beverages do
      resources :servings, only: [:new, :create, :edit, :update, :destroy, :index, :show]
      post 'active', on: :member
      post 'inactive', on: :member

    end

    resources :orders, only: [:new, :create, :show, :index] do
      post 'close_order', on: :member
      get 'result', on: :member
      resources :order_items, only: [:new, :create]
    end

    resources :discounts do
      resources :discount_servings, only: [:new, :create]
    end

  end
  get 'search', to: 'search#search'

  namespace :api do
    namespace :v1 do
      resources :restaurants do
        resources :orders, only: [:show, :index] do
          post 'in_preparation', on: :member
          post 'ready', on: :member
          post 'canceled', on: :member
        end
      end
    end
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :user
  has_many :employees, dependent: :destroy
  
  has_many :menu_items
  has_many :dishes, dependent: :destroy
  has_many :beverages, dependent: :destroy
  has_many :discounts

  has_many :operating_days
  
  has_many :markers
  has_many :menus
  has_many :orders

  validates :comercial_name, :registered_name, :cnpj, :address, :phone, :email, presence: true
  validates :phone, length: { in: 10..11 }
  validates :user, :code, :registered_name, :cnpj, uniqueness: true
  validate :cnpj_must_be_valid

  before_create :generate_unique_code

  after_destroy :remove_user_association

  def all_operating_days_added?
    operating_days.length < 7
  end

  private

  def cnpj_must_be_valid
    errors.add(:cnpj, "não é válido") unless CNPJ.valid?(cnpj)
  end

  def generate_unique_code
    loop do
      self.code = SecureRandom.alphanumeric(6).upcase
      break unless Restaurant.exists?(code: code)
    end
  end

  def remove_user_association
    user.update(restaurant: nil)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy, :show]

  def index
    @restaurants = Restaurant.all
  end


  def show
    @markers = @restaurant.markers
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = current_user.build_restaurant(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: "Restaurante cadastrado!"
    else
      current_user.restaurant = nil
      flash.now[:notice] = "Não foi possível registrar o restaurante"
      render :new, status: :unprocessable_entity
    end
  end 

  def edit 
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: "Restaurante Atualizado com Sucesso"
    else 
      flash.now[:notice] = "Não foi possível atualizar o restaurante"
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @restaurant.destroy
    redirect_to new_restaurant_path, notice: 'Restaurante Excluido com Sucesso!'
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def authorize_user!
    redirect_to root_path, alert: "Acesso não autorizado." unless @restaurant.user == current_user
  end

  def restaurant_params
    params.require(:restaurant).permit(
      :registered_name,
      :comercial_name,
      :cnpj,
      :address,
      :phone,
      :email
    )
  end

end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<div class="container mx-auto px-5 mt-10 max-w-lg">
  

  <%= form_with(model: @restaurant, class: "bg-white shadow-md rounded-lg p-6 space-y-6") do |f| %>
    
    <div>
      <%= f.label :registered_name, class: "block text-sm font-medium text-gray-700" %>
      <%= f.text_field :registered_name, required: true, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:ring-blue-500 focus:border-blue-500" %>
    </div>

    <div>
      <%= f.label :comercial_name, class: "block text-sm font-medium text-gray-700" %>
      <%= f.text_field :comercial_name, required: true, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:ring-blue-500 focus:border-blue-500" %>
    </div>

    <div>
      <%= f.label :cnpj, class: "block text-sm font-medium text-gray-700" %>
      <%= f.text_field :cnpj, required: true, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:ring-blue-500 focus:border-blue-500" %>
    </div>

    <div>
      <%= f.label :address, class: "block text-sm font-medium text-gray-700" %>
      <%= f.text_field :address, required: true, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:ring-blue-500 focus:border-blue-500" %>
    </div>

    <div>
      <%= f.label :phone, class: "block text-sm font-medium text-gray-700" %>
      <%= f.text_field :phone, 
      class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:ring-blue-500 focus:border-blue-500",
      required: true,
      placeholder: "(XX) XXXXX-XXXX",
      data: {
        controller: "phone-mask",
        action: "input->phone-mask#update blur->phone-mask#clean",
        phone_mask_target: "field"
      }
       %>
    </div>

    <div>
      <%= f.label :email, class: "block text-sm font-medium text-gray-700" %>
      <%= f.email_field :email, required: true, class: "mt-1 block w-full rounded-md border-gray-300 shadow-sm focus:ring-blue-500 focus:border-blue-500" %>
    </div>

    <div>
      <%= f.submit  class: "w-full bg-blue-600 text-white py-2 px-4 rounded-lg hover:bg-blue-500 focus:ring-2 focus:ring-offset-2 focus:ring-blue-500" %>
    </div>
  <% end %>
</div>

app/views/restaurants/edit.html.erb
<h1 class="text-2xl font-bold text-gray-800 mb-6">Editar Restaurante: <%= @restaurant.comercial_name %></h1>

<%= render "form" %>

app/views/restaurants/new.html.erb
<h1 class="text-2xl font-bold text-gray-800 mb-6">Registro do Restaurante</h1>


<%= render 'form' %>

app/views/restaurants/show.html.erb
<div class="container mx-auto px-5 mt-10">
  <h1 class="text-3xl font-bold text-gray-800 mb-6"><%= @restaurant.comercial_name %></h1>

  <div class="bg-white shadow-md rounded-lg p-6 space-y-4">
    <% [
      [Restaurant.human_attribute_name(:registered_name), @restaurant.registered_name],
      [Restaurant.human_attribute_name(:cnpj), @restaurant.cnpj],
      [Restaurant.human_attribute_name(:address), @restaurant.address],
      [Restaurant.human_attribute_name(:phone), @restaurant.phone],
      [Restaurant.human_attribute_name(:email), @restaurant.email],
      [Restaurant.human_attribute_name(:code), @restaurant.code]
    ].each do |label, value| %>
      <div>
        <strong class="text-gray-700"><%= label %>:</strong>
        <p class="text-gray-600"><%= value %></p>
      </div>
    <% end %>

    <div class="flex space-x-4">
      <%= link_to 'Editar Restaurante', edit_restaurant_path(@restaurant), class: "bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-500" %>
      <%= button_to 'Deletar Restaurante', restaurant_path(@restaurant), method: :delete, class: "bg-red-600 text-white px-4 py-2 rounded-lg hover:bg-red-500" %>
    </div>
  </div>

  <div class="mt-8 bg-white shadow-md rounded-lg p-6">
    <h2 class="text-xl font-bold text-gray-800 mb-4">Descontos Operantes:</h2>
    <div class="space-y-2">
      <% @restaurant.discounts.active.each do |discount| %>
        <p class="text-gray-700"><%= link_to discount.name, restaurant_discount_path(discount) %></p>
      <% end %>
    </div>
    <%= link_to 'Adicionar Desconto', new_restaurant_discount_path(@restaurant), class: "bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-500 mt-4 inline-block" %>
  </div>

  <div class="mt-8 bg-white shadow-md rounded-lg p-6 space-y-8">
    <div>
      <h2 class="text-xl font-bold text-gray-800 mb-4">Pratos</h2>
      <ul class="space-y-2">
        <% @restaurant.dishes.each do |dish| %>
          <li class="flex justify-between items-center bg-gray-100 p-4 rounded-lg">
            <%= link_to dish.name, restaurant_dish_path(@restaurant, dish), class: "text-blue-600 hover:underline" %>
            <span class="text-sm text-gray-600"><%= t(dish.status) %></span>
          </li>
        <% end %>
      </ul>
    </div>
    <div>
      <h2 class="text-xl font-bold text-gray-800 mb-4">Bebidas</h2>
      <ul class="space-y-2">
        <% @restaurant.beverages.each do |beverage| %>
          <li class="flex justify-between items-center bg-gray-100 p-4 rounded-lg">
            <%= link_to beverage.name, restaurant_beverage_path(@restaurant, beverage), class: "text-blue-600 hover:underline" %>
            <span class="text-sm text-gray-600"><%= t(beverage.status) %></span>
          </li>
        <% end %>
      </ul>
    </div>
  </div>

  <div class="mt-8 bg-white shadow-md rounded-lg p-6 flex space-x-4">
    <%= link_to 'Adicionar um prato', new_restaurant_dish_path(@restaurant), class: "bg-green-600 text-white px-4 py-2 rounded-lg hover:bg-green-500" %>
    <%= link_to 'Adicionar uma bebida', new_restaurant_beverage_path(@restaurant), class: "bg-indigo-600 text-white px-4 py-2 rounded-lg hover:bg-indigo-500" %>
  </div>

  <div class="mt-8 bg-white shadow-md rounded-lg p-6">
    <h2 class="text-xl font-bold text-gray-800 mb-4">Marcadores de Pratos do Restaurante</h2>
    <div class="space-y-2">
      <% @markers.each do |marker| %>
        <p class="text-gray-700"><%= marker.name %></p>
      <% end %>
    </div>
    <%= link_to 'Adicionar um Marcador', new_restaurant_marker_path(@restaurant), class: "bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-500 mt-4 inline-block" %>
  </div>

  <div class="mt-8 bg-white shadow-md rounded-lg p-6">
    <h2 class="text-xl font-bold text-gray-800 mb-4">Horário de Funcionamento</h2>
    <ul class="space-y-4">
      <% @restaurant.operating_days.order(:week_day).each do |day| %>
        <li class="bg-gray-100 p-4 rounded-lg">
          <%= link_to restaurant_operating_day_path(@restaurant, day), class: "block" do %>
            <p class="font-bold text-gray-700"><%= I18n.t(day.week_day) %></p>
            <% if day.open %>
              <p class="text-sm text-gray-600">
                <%= OperatingDay.human_attribute_name(:opening_time) %>: <%= I18n.localize(day.opening_time, format: :short_time) %>
              </p>
              <p class="text-sm text-gray-600">
                <%= OperatingDay.human_attribute_name(:closing_time) %>: <%= I18n.localize(day.closing_time, format: :short_time) %>
              </p>
            <% else %>
              <p class="text-sm text-red-600">Fechado</p>
            <% end %>
          <% end %>
        </li>
      <% end %>
    </ul>
    <% if @restaurant.all_operating_days_added? %>
      <%= link_to 'Adicionar Horário de Funcionamento', new_restaurant_operating_day_path(@restaurant), class: "bg-blue-600 text-white px-4 py-2 rounded-lg hover:bg-blue-500 mt-4 inline-block" %>
    <% end %>
  </div>
</div>